# Generated by Django 2.2.10 on 2024-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_auto_20240702_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='location',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
    ]
