# Generated by Django 2.2.10 on 2024-07-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_auto_20240704_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
