# Generated by Django 2.2.10 on 2024-07-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='number_of_candidates',
            field=models.IntegerField(default=1, verbose_name='Number of Candidates'),
        ),
    ]
